{pkgs}: {
  deps = [
    pkgs.run
    pkgs.glibcLocales
    pkgs.chromedriver
    pkgs.libcxx
    pkgs.zlib
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.pkg-config
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.freetype
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.cacert
    pkgs.libGLU
    pkgs.libGL
    pkgs.python311Packages.flask
    pkgs.python312Packages.flask
  ];
}
